services:
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      pgdata:
        - pgdata:/var/lib/postgresql/data
      adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080

  infinitymint:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
      - 80:80
    depends_on:
      - redis
