name: Continuous Deployment
on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build application
        uses: borales/actions-yarn@v4
        env:
          CI: false
        with:
          cmd: build
      
      - name: Serve react
        run: cp -r build /var/www/web_eth/
