name: Continuous Deployment
on:
	push:
		branches:
		- master

jobs:
  	deployment:
    	runs-on: self-hosted
    	steps:
		- name: Checkout main branch
			uses: actions/checkout@v2

		- name: Setup Node.js
			uses: actions/setup-node@v3
			with:
			node-version: '18.12.1'
		- run: npm ci --verbose
		- run: npm run build

		- name: Serve react
			run: cp -r build/* /var/www/magicmirror/html/

		- name: Serve API
			run: cp -r . /var/www/magicmirror/api
