name: Continuous Deployment
on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build
      
      - name: Serve react
        run: cp -r build /var/www/web_eth/
      
      - name: Deploy API
        run: cp -r * /var/www/web_eth/api
